version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - goconst
    - misspell
    - prealloc
    - revive
    - unparam

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

formatters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/steipete/goplaces

linters-settings:
  revive:
    rules:
      - name: early-return
      - name: empty-lines
      - name: errorf
      - name: unexported-return

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - dupl
        - gosec
